import { useState } from 'react';
import { conditionFields, conditionSources, memoryProposalsEnabled, parseTriggerInput, removeSchemaField, setMemoryProposals, setSchemaField, updateIntegerConfig, type TriggerFieldType, type TriggerSchema, type WorkflowEdge, type WorkflowNode, type WorkflowNodeKind } from './workflow-model.js';
import { Field } from './ui.js';

export type InspectorTab = 'instructions' | 'skills' | 'connections' | 'runtime';
export type OpenRouterModel = { id: string; structuredOutput: boolean };

export const blockHelp: Partial<Record<WorkflowNodeKind, string>> = {
  trigger: 'Starts a run from manual input or a signed webhook.', agent: 'Runs instructions within its response schema and policy bounds.', condition: 'Routes one True and one False branch from validated fields.', approval: 'Pauses a sensitive MCP effect for a reviewer.', mcp: 'Calls one granted Capability with validated inputs.', memory: 'Reads permitted, bounded workflow memory.', end: 'Completes the run.',
};

export function Inspector({ node, nodes, edges, tab, setTab, updateNode, live, model, setModel, maxSteps, setMaxSteps, openRouterModels, openRouterConnectionState, onStart, startReason }: { node: WorkflowNode | undefined; nodes: readonly WorkflowNode[]; edges: readonly WorkflowEdge[]; tab: InspectorTab; setTab: (tab: InspectorTab) => void; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, 'title' | 'instructions' | 'config'>>) => void; live: boolean; model: string; setModel: (model: string) => void; maxSteps: number; setMaxSteps: (steps: number) => void; publishedId?: string | undefined; openRouterModels: readonly OpenRouterModel[]; openRouterConnectionState: string; onStart?: (input: Record<string, unknown>) => void; startReason?: string }) {
  if (node === undefined) return <aside className="inspector"><div className="panel-title"><div><small>Workflow</small><strong>No step selected</strong></div></div><div className="inspector-content"><p>Add a Trigger to begin, or select a step to edit its settings.</p></div></aside>;
  return <aside className="inspector"><div className="panel-title"><div><small>{node.kind}</small><strong>{node.title}</strong></div></div>{!live && <div className="inspector-tabs">{(['instructions','skills','connections','runtime'] as InspectorTab[]).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item[0]!.toUpperCase() + item.slice(1)}</button>)}</div>}{tab === 'instructions' && <div className="inspector-content"><Field label="Step name"><input value={node.title} onChange={(event) => updateNode(node.id, { title: event.target.value })} /></Field><Field label="System instructions"><textarea rows={8} value={node.instructions} onChange={(event) => updateNode(node.id, { instructions: event.target.value })} /></Field><div className="variable-row"><span>Available variables</span><button type="button">Insert variable</button></div><div className="token-row"><code>request.summary</code><code>account.risk_tier</code></div></div>}{tab === 'skills' && <div className="inspector-content"><AttachedItem name="Customer policy" type="Verified skill" /><AttachedItem name="Account resolver" type="Workspace skill" /><button className="dashed-button">Attach skill</button></div>}{tab === 'connections' && <div className="inspector-content"><AttachedItem name="Customer data" type="Remote MCP connection" /><AttachedItem name="Billing actions" type="MCP connection with approval" /><AttachedItem name="Support intake" type="Webhook connection" /><button className="dashed-button">Add connection</button></div>}{tab === 'runtime' && <div className="inspector-content"><Field label="Model"><select value={model} onChange={(event) => setModel(event.target.value)}><option>Atlas 2.1</option><option>Compact 1.4</option></select></Field><Field label="Maximum steps"><input type="number" min="1" value={maxSteps} onChange={(event) => setMaxSteps(Math.max(1, Number(event.target.value) || 1))} /></Field><Field label="Approval policy"><select defaultValue="account"><option value="account">Required for account changes</option><option value="always">Always required</option></select></Field><label className="switch-row"><span><strong>Trace this step</strong><small>Capture inputs, tool calls, and latency</small></span><input type="checkbox" defaultChecked /></label></div>}{live && (node.kind === 'memory' ? <MemorySettings key={node.id} node={node} updateNode={updateNode} /> : node.kind === 'agent' ? <AgentSettings key={node.id} node={node} updateNode={updateNode} openRouterModels={openRouterModels} openRouterConnectionState={openRouterConnectionState} /> : <StepSettings key={node.id} node={node} nodes={nodes} edges={edges} updateNode={updateNode} onStart={onStart} startReason={startReason} />)}</aside>;
}
function MemorySettings({ node, updateNode }: { node: WorkflowNode; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, 'config'>>) => void }) {
  const [limit, setLimit] = useState(String(node.config?.['limit'] ?? ''));
  const [maxChars, setMaxChars] = useState(String(node.config?.['maxChars'] ?? ''));
  const [errors, setErrors] = useState<Record<'limit' | 'maxChars', string | undefined>>({ limit: undefined, maxChars: undefined });
  const change = (key: 'limit' | 'maxChars', value: string, minimum: number, maximum: number, setValue: (next: string) => void) => {
    setValue(value);
    const result = updateIntegerConfig(node.config ?? {}, key, value, minimum, maximum);
    setErrors((current) => ({ ...current, [key]: result.error }));
    if (result.config) updateNode(node.id, { config: result.config });
  };
  return <div className="inspector-content"><Field label="Memory item limit"><input type="number" min="1" max="20" step="1" inputMode="numeric" value={limit} aria-invalid={errors.limit !== undefined} aria-describedby={errors.limit ? 'memory-limit-error' : undefined} onChange={(event) => change('limit', event.target.value, 1, 20, setLimit)} /></Field>{errors.limit && <span id="memory-limit-error" role="alert">{errors.limit}</span>}<Field label="Memory character budget"><input type="number" min="1" max="4000" step="1" inputMode="numeric" value={maxChars} aria-invalid={errors.maxChars !== undefined} aria-describedby={errors.maxChars ? 'memory-character-budget-error' : undefined} onChange={(event) => change('maxChars', event.target.value, 1, 4000, setMaxChars)} /></Field>{errors.maxChars && <span id="memory-character-budget-error" role="alert">{errors.maxChars}</span>}<PolicySettings config={node.config ?? {}} update={(policy) => updateNode(node.id, { config: { ...(node.config ?? {}), policy } })} /></div>;
}
function PolicySettings({ config, update }: { config: Record<string, unknown>; update: (policy: Record<string, number>) => void }) {
  const policy = config['policy'] as Record<string, number> ?? { milliseconds: 30000, attempts: 1, tokens: 0, cost: 0, toolRounds: 0, effects: 0 };
  const fields: readonly [keyof typeof policy, string, number, number][] = [['milliseconds', 'Deadline (ms)', 1, 86400000], ['attempts', 'Attempts', 1, 5], ['tokens', 'Token limit', 0, 100000], ['cost', 'Cost limit', 0, 1000], ['toolRounds', 'Tool rounds', 0, 20], ['effects', 'External effects', 0, 20]];
  return <><strong>Node policy</strong>{fields.map(([key, label, min, max]) => <Field key={key} label={label}><input type="number" min={min} max={max} step={key === 'cost' ? 'any' : '1'} value={policy[key]} onChange={(event) => { const value = Number(event.target.value); if (Number.isFinite(value) && value >= min && value <= max && (key === 'cost' || Number.isSafeInteger(value))) update({ ...policy, [key]: value }); }} /></Field>)}</>;
}
function AgentSettings({ node, updateNode, openRouterModels, openRouterConnectionState }: { node: WorkflowNode; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, 'config'>>) => void; openRouterModels: readonly OpenRouterModel[]; openRouterConnectionState: string }) {
  const config = node.config ?? {};
  const enabled = memoryProposalsEnabled(node.config ?? {});
  const guidance = 'Allowed types: task-fact and stated-preference. Every proposal needs text, sourceId, sourceDigest, and excerpt; a stated-preference also needs subject, while predecessorId is optional. Text and excerpt are each limited to 1000 characters; subject is limited to 200; return at most three proposals. sourceId and sourceDigest must exactly cite current validated input or a completed event. The server derives tenant, workflow, and owner scope; validates and redacts cited evidence; and rejects secrets, instructions, inferred traits, and unsourced claims.';
  const models = config['provider'] === 'openrouter' ? openRouterModels : [];
  const selectedModels = [...new Set([typeof config['model'] === 'string' ? config['model'] : '', ...models.map((item) => item.id)].filter(Boolean))];
  const update = (patch: Record<string, unknown>) => updateNode(node.id, { config: { ...config, ...patch } });
  const [schema, setSchema] = useState(JSON.stringify(config['responseSchema'] ?? {}, null, 2));
  const [schemaError, setSchemaError] = useState<string>();
  return <div className="inspector-content"><Field label="Provider"><select value={String(config['provider'] ?? 'azure-openai')} onChange={(event) => update({ provider: event.target.value, ...(event.target.value === 'openrouter' ? { openRouterOptIn: false } : {}) })}><option value="azure-openai">Azure OpenAI</option><option value="openrouter">OpenRouter</option></select></Field>{config['provider'] === 'openrouter' && <p className="inspector-help">Connection: {openRouterConnectionState}. Only certified exact models are shown; the server checks again before publish.</p>}<Field label="Exact model">{selectedModels.length > 0 ? <select value={String(config['model'] ?? '')} onChange={(event) => update({ model: event.target.value, ...(config['fallback'] === event.target.value ? { fallback: undefined } : {})})}>{selectedModels.map((item) => <option key={item} value={item}>{item}</option>)}</select> : <input value={String(config['model'] ?? '')} onChange={(event) => update({ model: event.target.value })} />}</Field><Field label="Fallback model"><select value={String(config['fallback'] ?? '')} onChange={(event) => update({ fallback: event.target.value || undefined })}><option value="">No fallback</option>{selectedModels.filter((item) => item !== config['model']).map((item) => <option key={item} value={item}>{item}</option>)}</select></Field>{config['provider'] === 'openrouter' && <label className="switch-row"><span><strong>Allow OpenRouter</strong><small>Use this tenant's verified connection; no key is stored in the draft.</small></span><input type="checkbox" checked={config['openRouterOptIn'] === true} onChange={(event) => update({ openRouterOptIn: event.target.checked })} /></label>}<Field label="Response schema (JSON)"><textarea rows={8} value={schema} aria-invalid={schemaError !== undefined} aria-describedby={schemaError ? 'response-schema-error' : undefined} onChange={(event) => setSchema(event.target.value)} onBlur={() => { try { const value: unknown = JSON.parse(schema); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); update({ responseSchema: value }); setSchemaError(undefined); } catch { setSchemaError('Enter a JSON object.'); } }} /></Field>{schemaError && <span id="response-schema-error" role="alert">{schemaError}</span>}<PolicySettings config={config} update={(policy) => update({ policy })} /><label className="switch-row"><span><strong>Allow operational memory proposals</strong><small>Lets this Agent return an optional memoryProposals array.</small></span><input type="checkbox" checked={enabled} onChange={(event) => updateNode(node.id, { config: setMemoryProposals(config, event.target.checked) })} /></label><Field label="Copyable proposal guidance"><textarea rows={10} readOnly value={guidance} /></Field></div>;
}
function StepSettings({ node, nodes, edges, updateNode, onStart, startReason }: { node: WorkflowNode; nodes: readonly WorkflowNode[]; edges: readonly WorkflowEdge[]; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, "config">>) => void; onStart?: (input: Record<string, unknown>) => void; startReason?: string }) {
  if (node.kind === 'trigger') return <TriggerSettings node={node} updateNode={updateNode} onStart={onStart} startReason={startReason} />;
  if (node.kind === 'end') return <div className="inspector-content"><p>End completes the run and has no runtime settings.</p></div>;
  if (node.kind === 'condition') return <ConditionSettings node={node} nodes={nodes} edges={edges} updateNode={updateNode} />;
  if (node.kind === 'approval') return <ApprovalSettings node={node} nodes={nodes} edges={edges} updateNode={updateNode} />;
  const [value, setValue] = useState(JSON.stringify(node.config ?? {}, null, 2));
  const [error, setError] = useState(false);
  return <div className="inspector-content"><Field label="Step settings"><textarea rows={9} value={value} onChange={(event) => setValue(event.target.value)} onBlur={() => { try { const parsed: unknown = JSON.parse(value); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); updateNode(node.id, { config: parsed as Record<string, unknown> }); setError(false); } catch { setError(true); } }} /></Field>{error && <span role="alert">Enter a valid settings object.</span>}</div>;
}
function ConditionSettings({ node, nodes, edges, updateNode }: { node: WorkflowNode; nodes: readonly WorkflowNode[]; edges: readonly WorkflowEdge[]; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, 'config'>>) => void }) {
  const config = node.config ?? {}; const sources = conditionSources(nodes, edges, node.id); const source = sources.find((item) => item.id === config['source'] || config['source'] === 'input' && item.kind === 'trigger') ?? sources[0]; const fields = source ? conditionFields(source) : []; const field = fields.find(([name]) => name === config['field']) ?? fields[0];
  const update = (nextSource = source, nextField = field, equals: unknown = config['equals']) => nextSource && nextField && updateNode(node.id, { config: { source: nextSource.kind === 'trigger' ? 'input' : nextSource.id, field: nextField[0], equals } });
  if (!source || !field) return <div className="inspector-content"><p>Add and connect a Trigger or Agent with a string, number, or boolean field before configuring this Condition.</p></div>;
  const type = field[1];
  return <div className="inspector-content"><Field label="Source"><select value={source.id} onChange={(event) => { const next = sources.find((item) => item.id === event.target.value); const first = next && conditionFields(next)[0]; update(next, first, first?.[1] === 'boolean' ? false : first?.[1] === 'number' ? 0 : ''); }}><option value={source.id}>{source.kind === 'trigger' ? 'input' : source.title}</option>{sources.filter((item) => item.id !== source.id).map((item) => <option key={item.id} value={item.id}>{item.kind === 'trigger' ? 'input' : item.title}</option>)}</select></Field><Field label="Field"><select value={field[0]} onChange={(event) => { const next = fields.find(([name]) => name === event.target.value)!; update(source, next, next[1] === 'boolean' ? false : next[1] === 'number' ? 0 : ''); }}>{fields.map(([name, value]) => <option key={name} value={name}>{name} ({value})</option>)}</select></Field><Field label="Equals">{type === 'boolean' ? <select value={String(config['equals'])} onChange={(event) => update(source, field, event.target.value === 'true')}><option value="true">true</option><option value="false">false</option></select> : <input type={type === 'number' ? 'number' : 'text'} value={String(config['equals'] ?? '')} onChange={(event) => update(source, field, type === 'number' ? Number(event.target.value) : event.target.value)} />}</Field><p>Connect the labeled True and False exits to one successor each.</p></div>;
}
function ApprovalSettings({ node, nodes, edges, updateNode }: { node: WorkflowNode; nodes: readonly WorkflowNode[]; edges: readonly WorkflowEdge[]; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, 'config'>>) => void }) {
  const next = nodes.find((candidate) => edges.some((edge) => edge.from === node.id && edge.to === candidate.id)); const timeout = Number(node.config?.['timeoutMs'] ?? 3600000);
  return <div className="inspector-content"><Field label="Approval timeout (ms)"><input type="number" min="1" max="86400000" step="1" value={timeout} onChange={(event) => { const value = Number(event.target.value); if (Number.isSafeInteger(value) && value >= 1 && value <= 86400000) updateNode(node.id, { config: { timeoutMs: value } }); }} /></Field><p>{next?.kind === 'mcp' ? `This Approval waits for an administrator, then permits the immediately following MCP effect: ${next.title}. The review is bound to this run; there is no separate approval inbox.` : 'Connect this Approval directly to an MCP effect to publish.'}</p><p>Run History shows the wait deadline, decision, and receipt. Rejections stop the effect, expired or stale decisions must be refreshed, and an unknown external effect needs reconciliation.</p><p>Canva is only an example when a certified Connector Installation grants a Capability, the Agent is allowed to use it, and a published run reaches this Approval node.</p></div>;
}
function TriggerSettings({ node, updateNode, onStart, startReason }: { node: WorkflowNode; updateNode: (id: string, patch: Partial<Pick<WorkflowNode, 'config'>>) => void; onStart?: (input: Record<string, unknown>) => void; startReason?: string }) {
  const config = node.config ?? {}; const schema = config['inputSchema'] as TriggerSchema ?? { type: 'object', properties: {}, required: [], additionalProperties: false };
  const update = (next: TriggerSchema, mode = config['mode'] === 'webhook' ? 'webhook' : 'manual') => updateNode(node.id, { config: { mode, inputSchema: next } });
  return <div className="inspector-content"><Field label="Trigger mode"><select value={String(config['mode'] ?? 'manual')} onChange={(event) => update(schema, event.target.value)}><option value="manual">Manual</option><option value="webhook">Webhook</option></select></Field><strong>Input fields</strong>{Object.entries(schema.properties).map(([name, field]) => <TriggerField key={name} name={name} type={field.type} required={schema.required.includes(name)} save={(nextName, type, required) => update(setSchemaField(schema, nextName, type, required, name))} remove={() => update(removeSchemaField(schema, name))} />)}<button type="button" className="dashed-button" onClick={() => update(setSchemaField(schema, `field${Object.keys(schema.properties).length + 1}`, 'string', false))}>Add input field</button>{config['mode'] === 'manual' && onStart && <ManualInput schema={schema} onStart={onStart} startReason={startReason} />}</div>;
}
function ManualInput({ schema, onStart, startReason }: { schema: TriggerSchema; onStart: (input: Record<string, unknown>) => void; startReason?: string }) {
  const [values, setValues] = useState<Record<string, unknown>>({}); const [errors, setErrors] = useState<Record<string, string>>({});
  const submit = () => { const parsed = parseTriggerInput(schema, values); if (parsed.errors) { setErrors(parsed.errors); return; } onStart(parsed.input ?? {}); };
  return <section><strong>Sample event and manual start</strong>{Object.entries(schema.properties).map(([name, field]) => <Field key={name} label={`${name}${schema.required.includes(name) ? ' (required)' : ''}`} error={errors[name]}>{field.type === 'boolean' ? <select value={String(values[name] ?? '')} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value === 'true' }))}><option value="">Choose</option><option value="true">True</option><option value="false">False</option></select> : field.type === 'array' ? <textarea aria-label={`${name} items`} placeholder="One item per line" onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value.split('\n').filter(Boolean) }))} /> : field.type === 'object' ? <textarea aria-label={`${name} fields`} placeholder="One name: value per line" onChange={(event) => setValues((current) => ({ ...current, [name]: Object.fromEntries(event.target.value.split('\n').map((line) => line.split(':').map((part) => part.trim())).filter(([key]) => key)) }))} /> : <input type={field.type === 'number' ? 'number' : 'text'} value={String(values[name] ?? '')} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} />}</Field>)}<button type="button" className="button-secondary" onClick={submit} disabled={startReason !== undefined} aria-describedby={startReason ? 'manual-start-reason' : undefined}>Start run</button>{startReason && <p id="manual-start-reason" className="field-help">{startReason}</p>}</section>;
}
function TriggerField({ name, type, required, save, remove }: { name: string; type: TriggerFieldType; required: boolean; save: (name: string, type: TriggerFieldType, required: boolean) => void; remove: () => void }) {
  const [nextName, setNextName] = useState(name); const [nextType, setNextType] = useState(type); const [nextRequired, setNextRequired] = useState(required);
  return <div className="trigger-field"><input aria-label={`${name} name`} value={nextName} onChange={(event) => setNextName(event.target.value)} onBlur={() => save(nextName, nextType, nextRequired)} /><select aria-label={`${name} type`} value={nextType} onChange={(event) => { const value = event.target.value as TriggerFieldType; setNextType(value); save(nextName, value, nextRequired); }}><option value="string">Text</option><option value="number">Number</option><option value="boolean">True or false</option><option value="object">Object</option><option value="array">List</option></select><label><input type="checkbox" checked={nextRequired} onChange={(event) => { setNextRequired(event.target.checked); save(nextName, nextType, event.target.checked); }} /> Required</label><button type="button" onClick={remove}>Remove</button></div>;
}
export function AttachedItem({ name, type }: { name: string; type: string }) { return <div className="attached-item"><i /><span><strong>{name}</strong><small>{type}</small></span><button>•••</button></div>; }
