import { useRef, useState, type MouseEvent as ReactMouseEvent, type RefObject } from 'react';
import { scrollBehavior, type Navigate } from './app-routes.js';
import { Dialog } from './ui.js';

export function Landing({ navigate, authEnabled }: { navigate: Navigate; authEnabled: boolean }) {
  const [activeCapability, setActiveCapability] = useState(0);
  const [drawer, setDrawer] = useState<'studio' | 'governance'>();
  const opener = useRef<HTMLButtonElement>(null);
  const capabilities = [
    { title: 'Compose the work', text: 'Map decisions, tools, and human checkpoints on one inspectable canvas.', stat: '5 typed steps' },
    { title: 'Bring your harness', text: 'Attach skills, remote connectors, or stdio MCP servers without reshaping the workflow.', stat: '12 adapters' },
    { title: 'Operate with evidence', text: 'Give admins trace-level oversight while operators see only the signals needed to act.', stat: '100% traced' },
  ];
  const active = capabilities[activeCapability]!;
  const openDrawer = (next: 'studio' | 'governance', event: ReactMouseEvent<HTMLButtonElement>) => { opener.current = event.currentTarget; setDrawer(next); };
  const closeDrawer = () => setDrawer(undefined);
  return <><section className="hero page-shell"><div className="hero-copy reveal"><p className="eyebrow">Agent operations, under control</p><h1>Build AI workflows your team can actually operate.</h1><p className="hero-deck">Design the workflow, attach its tools, and know what happened after every run.</p><div className="hero-actions"><button className="button" onClick={() => navigate('studio')}>Open the studio</button><button className="link-button" onClick={() => document.getElementById('platform')?.scrollIntoView({ behavior: scrollBehavior() })}>See how it works <span>↘</span></button></div></div><WorkflowPreview /></section>
  <section className="proof-strip" aria-label="Platform compatibility"><div className="marquee-track"><span>MCP</span><span>OpenTelemetry</span><span>Clerk</span><span>Prometheus</span><span>Grafana</span><span>Webhooks</span><span aria-hidden="true">MCP</span><span aria-hidden="true">OpenTelemetry</span><span aria-hidden="true">Clerk</span><span aria-hidden="true">Prometheus</span></div></section>
  <section id="platform" className="capability-section page-shell"><div className="section-heading"><h2>One surface for building.<br />One for knowing.</h2><p>Operators get a focused workspace. Admins get the evidence needed to keep every automation accountable.</p></div><div className="capability-grid"><article className="capability-visual studio-visual"><div className="mini-toolbar"><span>Support resolution</span><b>Example draft</b></div><div className="mini-canvas"><div className="mini-node n1"><small>Input</small><strong>Request</strong></div><div className="mini-node n2 active"><small>Agent</small><strong>Reason</strong></div><div className="mini-node n3"><small>Tool</small><strong>Resolve</strong></div><i className="mini-line l1" /><i className="mini-line l2" /></div></article><article className="capability-copy"><span className="index">01</span><h3>Solution Studio</h3><p>Configure instructions, skills, MCP servers, connectors, policies, and approvals without losing sight of the actual flow.</p><button className="inline-link" onClick={(event) => openDrawer('studio', event)}>How Studio works <span>→</span></button></article><article className="capability-copy governance-copy"><span className="index">02</span><h3>Governance</h3><p>Review the authenticated fixture preview for example usage, latency, failures, cost, and access signals.</p><button className="inline-link" onClick={(event) => openDrawer('governance', event)}>How Governance works <span>→</span></button></article><article className="capability-visual governance-visual"><div className="metric-big"><span>Example success rate</span><strong>97.4%</strong><small>Fixture preview</small></div><div className="line-chart" aria-label="Example success rate trend">{[32,40,35,54,49,61,58,73,69,82,88,91].map((height,index) => <i key={index} style={{ height: `${height}%` }} />)}</div></article></div></section>
  <section className="capability-accordion page-shell"><h2>Designed around the hard parts.</h2><div className="accordion-layout"><div className="accordion-list">{capabilities.map((capability,index) => <button key={capability.title} className={activeCapability === index ? 'active' : ''} onClick={() => setActiveCapability(index)}><span>0{index + 1}</span><strong>{capability.title}</strong><i>+</i></button>)}</div><div className="accordion-detail" aria-live="polite"><p>{active.text}</p><strong>{active.stat}</strong><div className={`detail-art art-${activeCapability}`}><i /><i /><i /></div></div></div></section>
  <section className="landing-cta page-shell"><div><p>Start with the work you already know.</p><h2>Make the next workflow visible from the first step.</h2></div><button className="button button-light" onClick={() => navigate('studio')}>Build a workflow</button></section>{drawer && <LandingDrawer surface={drawer} navigate={navigate} close={closeDrawer} opener={opener} />}<Footer navigate={navigate} authEnabled={authEnabled} /></>;
}

export function WorkflowPreview() { return <div className="hero-product reveal delay-one" aria-label="Example workflow builder preview"><div className="window-bar"><span className="window-dots"><i /><i /><i /></span><span>Example workflow / Refund triage</span><b>Example</b></div><div className="preview-body"><aside><strong>Workflow</strong><span className="selected">Canvas</span><span>Harness</span><span>Tests</span><span>Versions</span></aside><div className="preview-canvas"><svg className="preview-connectors" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="M 31 55 L 37 37 M 64 37 L 69 59" /><path className="preview-connectors-mobile" d="M 30 55 L 43 37 M 69 37 L 70 68" /></svg><div className="preview-node node-a"><small>TRIGGER</small><strong>Ticket created</strong><span>Example webhook</span></div><div className="preview-node node-b"><small>AGENT</small><strong>Assess request</strong><span>Example · 3 skills</span></div><div className="preview-node node-c"><small>ACTION</small><strong>Issue refund</strong><span>Needs approval</span></div><div className="run-toast"><i /> Example run: 2.8s</div></div><aside className="preview-inspector"><strong>Harness</strong><label>Model<span>Example model</span></label><label>Skills<span>3 shown</span></label><label>Policy<span>Human approval</span></label></aside></div></div>; }

function LandingDrawer({ surface, navigate, close, opener }: { surface: 'studio' | 'governance'; navigate: Navigate; close: () => void; opener: RefObject<HTMLButtonElement | null> }) {
  const content = surface === 'studio' ? { title: 'Solution Studio', purpose: 'Author a workflow as an inspectable graph before saving a revision.', first: 'Start with a Trigger, then connect the steps that handle the work.', visible: 'You will see the canvas, node settings, saved revision state, checks, and published run evidence.', action: 'Open Solution Studio' } : { title: 'Governance fixture preview', purpose: 'Review the shape of governance information without claiming live operational data.', first: 'Open the authenticated fixture preview to inspect its example portfolio and trace view.', visible: 'You will see fixture-only metrics, example service health, workflow rows, and a trace drawer.', action: 'Open Governance preview' };
  const close2 = () => { close(); requestAnimationFrame(() => opener.current?.focus()); };
  return <Dialog labelledBy="landing-drawer-title" onClose={close2} className={`landing-drawer ${surface}`}><div className="drawer-heading"><div><small>Product guide</small><h2 id="landing-drawer-title">{content.title}</h2></div><button onClick={close2} aria-label="Close guide">×</button></div><dl><div><dt>Purpose</dt><dd>{content.purpose}</dd></div><div><dt>First action</dt><dd>{content.first}</dd></div><div><dt>Visible information</dt><dd>{content.visible}</dd></div></dl><button className="button drawer-action" onClick={() => { close(); navigate(surface); }}>{content.action}</button></Dialog>;
}

export function Footer({ navigate, authEnabled }: { navigate: Navigate; authEnabled: boolean }) { return <footer className="footer page-shell"><button className="wordmark" onClick={() => navigate('home')}><span className="brand-mark"><i /><i /><i /></span><span>threadline</span></button><p>AI workflow infrastructure for teams that need proof, not promises.</p><nav><button onClick={() => navigate('studio')}>Studio</button>{!authEnabled && <button onClick={() => navigate('governance')}>Governance preview</button>}</nav><small>© 2026 Threadline Systems</small></footer>; }
