import { useEffect, useState } from 'react';
import type { PlatformApi, Projection } from './platform-api.js';
import { WorkflowMemoryPanel } from './workflow-memory-panel.js';

export function MemoryImportPanel({ api, tenantId, definitionId, admin, definitions, definitionsState, runs, runsState }: { api: PlatformApi; tenantId: string; definitionId: string; admin: boolean; definitions: Projection | undefined; definitionsState: 'loading' | 'ready' | 'failed'; runs: Projection | undefined; runsState: 'loading' | 'ready' | 'failed' }) {
  const [imports, setImports] = useState<Projection>(); const [sourceDefinitionId, setSourceDefinitionId] = useState(''); const [message, setMessage] = useState<string>();
  const refresh = async (active = () => true) => { const nextImports = await api.projection(tenantId, 'workflow-memory-imports'); if (active()) setImports(nextImports); };
  useEffect(() => { let active = true; setImports(undefined); setSourceDefinitionId(''); setMessage(undefined); void refresh(() => active).catch(() => active && setMessage('Memory imports could not be loaded.')); return () => { active = false; }; }, [api, tenantId, definitionId]);
  const add = async () => { try { await api.command({ tenantId, owner: 'workflow', name: 'import-memory', expectedVersion: 0, arguments: { id: definitionId, sourceDefinitionId } }); setSourceDefinitionId(''); setMessage('Memory source attached to this published revision.'); await refresh(); } catch { setMessage('Memory import was not accepted.'); } };
  const revoke = async (id: string, version: number) => { try { await api.command({ tenantId, owner: 'workflow', name: 'revoke-memory-import', expectedVersion: version, arguments: { id, reason: 'Administrator revoked this attachment.' } }); setMessage('Memory source revoked for future retrieval.'); await refresh(); } catch { setMessage('Memory import revocation was not accepted.'); } };
  const scoped = imports?.records.filter((item) => item['targetDefinitionId'] === definitionId) ?? [];
  return <><section className="memory-import-panel" aria-label="Workflow memory imports"><strong>Memory imports</strong><span>Published source definitions are attached to this exact target revision. Revocation affects future retrieval only.</span>{imports === undefined ? <p>Loading memory imports.</p> : scoped.length === 0 ? <p>No Memory Imports are attached to this definition.</p> : scoped.map((item) => <p key={String(item['id'])}>Source definition {String(item['sourceDefinitionId'])} · target revision {String(item['targetRevision'])} · {String(item['state'])} {admin && item['state'] === 'active' && <button onClick={() => void revoke(String(item['id']), Number(item['version']))}>Revoke</button>}</p>)}{admin && definitionsState === 'loading' && <p>Loading source definitions.</p>}{admin && definitionsState === 'failed' && <p role="alert">Source definitions could not be loaded.</p>}{admin && definitionsState === 'ready' && <div><label>Source definition<select aria-label="Source definition" value={sourceDefinitionId} onChange={(event) => setSourceDefinitionId(event.target.value)}><option value="">Select published source</option>{definitions?.records.filter((item) => item['id'] !== definitionId).map((item) => <option key={String(item['draftId'])} value={String(item['draftId'])}>{String(item['draftId'])} · revision {String(item['revision'])}</option>)}</select></label><button disabled={!sourceDefinitionId} onClick={() => void add()}>Attach source</button></div>}{message && <span role="status">{message}</span>}</section><WorkflowMemoryPanel api={api} tenantId={tenantId} definitionId={definitionId} admin={admin} initialRuns={runs} initialRunsState={runsState} /></>;
}
