import { useEffect, useState } from 'react';
import { describeError, withRef, type PlatformApi, type Projection } from './platform-api.js';

export function OpenRouterConnectionPanel({ api, tenantId, admin, initialStatus, initialState }: { api: PlatformApi; tenantId: string; admin: boolean; initialStatus: Projection | undefined; initialState: 'loading' | 'ready' | 'failed' }) {
  const [status, setStatus] = useState<Projection>(); const [key, setKey] = useState(''); const [message, setMessage] = useState('');
  const refresh = async () => setStatus(await api.projection(tenantId, 'openrouter-connections'));
  useEffect(() => { setKey(''); setMessage(''); setStatus(initialStatus); }, [api, tenantId, initialStatus]);
  if (initialState === 'loading' && status === undefined) return <section className="connector-panel" aria-label="OpenRouter connection"><p>Loading provider connection status.</p></section>;
  if (initialState === 'failed' && status === undefined) return <section className="connector-panel" aria-label="OpenRouter connection"><p role="alert">Connection status could not be loaded.</p><button onClick={() => void refresh().catch(() => setMessage('Connection status could not be loaded.'))}>Refresh</button>{message && <p role="status">{message}</p>}</section>;
  const record = status?.records[0]; const version = Number(record?.['version'] ?? 0); const enabled = record?.['enabled'] === true;
  const act = async (action: 'connect' | 'rotate' | 'verify' | 'disconnect') => { try { await api.openRouterConnection(tenantId, action, version, action === 'connect' || action === 'rotate' ? key : undefined); setKey(''); setMessage(action === 'verify' ? 'Connection verified.' : action === 'disconnect' ? 'Connection disconnected.' : 'Connection saved and verified.'); await refresh(); } catch (error) { setKey(''); setMessage(withRef(describeError(error, { write: true }) === 'unavailable' ? 'OpenRouter connections are not available in this workspace yet.' : 'Connection request was denied, stale, or could not be verified.', error)); } };
  return <section className="connector-panel" aria-label="OpenRouter connection"><div className="pane-heading"><div><p>Provider connection</p><h2>OpenRouter</h2><span>{enabled ? 'Ready' : 'Not connected'}</span></div></div>{message && <p role="status">{message}</p>}{admin && <><label>OpenRouter API key<input type="password" value={key} onChange={(event) => setKey(event.target.value)} autoComplete="off" /></label>{enabled ? <div><button disabled={!key} onClick={() => void act('rotate')}>Rotate key</button><button onClick={() => void act('verify')}>Verify</button><button onClick={() => void act('disconnect')}>Disconnect</button></div> : <button disabled={!key} onClick={() => void act('connect')}>Connect and verify</button>}</>}{!admin && <p>An administrator can manage this connection.</p>}</section>;
}
