export function RunHistory({ records, admin, decide, reconcile, loadOlder, hasMore, loadingOlder }: { records: readonly Record<string, unknown>[]; admin: boolean; decide: (runId: string, bindingDigest: string, decision: 'approve' | 'reject', version: number) => void; reconcile: (runId: string, version: number, disposition: 'adopt' | 'no-effect') => void; loadOlder: () => void; hasMore: boolean; loadingOlder: boolean }) {
  return <section className="connector-panel run-history" aria-label="Run History"><div className="pane-heading"><div><p>Run History</p><h2>Accepted event outcomes</h2><span>Input values and effect arguments remain redacted. A stale decision must be refreshed; an unknown effect needs reconciliation.</span></div></div>{records.map((run) => {
    const id = typeof run['id'] === 'string' ? run['id'] : '';
    const version = typeof run['version'] === 'number' ? run['version'] : 0;
    const history = Array.isArray(run['history']) ? run['history'] as Record<string, unknown>[] : [];
    const effects = Array.isArray(run['effects']) ? run['effects'] as Record<string, unknown>[] : [];
    const summary = Array.isArray(run['inputSummary']) ? run['inputSummary'] as Record<string, unknown>[] : [];
    const waiting = run['waiting'] !== null && typeof run['waiting'] === 'object' ? run['waiting'] as Record<string, unknown> : undefined;
    const decision = history.findLast((event) => event['kind'] === 'approval' && (event['detail'] === 'approve' || event['detail'] === 'reject'))?.['detail'];
    const status = String(run['status']); const description = status === 'waiting-approval' ? 'Pending administrator decision before the bound external effect.' : status === 'unknown-outcome' ? 'The external effect may have occurred. Reconcile it before further action.' : decision === 'reject' ? 'The administrator rejected the bound external effect.' : history.some((event) => event['detail'] === 'APPROVAL_EXPIRED') ? 'The approval deadline expired; the effect was not sent.' : status === 'completed' ? 'The run completed with the receipts shown below.' : 'The run stopped before completing.';
    const review = waiting?.['review'] !== null && typeof waiting?.['review'] === 'object' ? waiting['review'] as Record<string, unknown> : undefined;
    return <article key={id} id={`run-${id}`}><div><strong>Run {id}</strong><p>Definition r{String(run['definitionRevision'])} · digest {String(run['definitionDigest']).slice(0, 12)} · {description}</p></div><p>Accepted input: {summary.length ? summary.map((field) => `${String(field['field'])} (${String(field['type'])})`).join(', ') : 'no fields'} · digest {String(run['inputDigest']).slice(0, 12)}</p>{waiting && <p>Waiting at {String(waiting['nodeId'])} until {String(waiting['expiresAt'])}.{review && <> Reviewing {String(review['capability'])} on {String(review['target'])}; fields: {Array.isArray(review['arguments']) ? (review['arguments'] as Record<string, unknown>[]).map((field) => `${String(field['name'])} (${String(field['type'])})`).join(', ') : 'redacted'}.</>}</p>}<ol>{history.map((event, index) => <li key={`${String(event['at'])}-${index}`}><time>{String(event['at'])}</time><span>{String(event['nodeId'])}</span><strong>{String(event['state'])}</strong>{event['kind'] === 'approval' && typeof event['detail'] === 'string' && <em>{event['detail'] === 'approve' ? 'approved' : event['detail'] === 'reject' ? 'rejected' : event['detail'] === 'APPROVAL_EXPIRED' ? 'expired' : 'awaiting decision'}</em>}{event['kind'] === 'mcp' && typeof event['detail'] === 'string' && event['detail'].startsWith('tool:') && <em>agent tool call {event['detail'].slice(5)}</em>}{event['kind'] === 'agent' && event['state'] === 'waiting' && <em>agent waiting for tool approval</em>}{event['receiptId'] ? <code>receipt {String(event['receiptId'])}</code> : null}</li>)}</ol>{effects.map((effect) => <p key={String(effect['id'])}>Effect {String(effect['nodeId'])}: {String(effect['state'])} · receipt {String(effect['id'])} · arguments digest {String(effect['argumentsDigest']).slice(0, 12)}</p>)}{admin && waiting && typeof waiting['bindingDigest'] === 'string' && <p><button onClick={() => decide(id, waiting['bindingDigest'] as string, 'approve', version)}>Approve</button><button onClick={() => decide(id, waiting['bindingDigest'] as string, 'reject', version)}>Reject</button></p>}{admin && status === 'unknown-outcome' && <p><button onClick={() => reconcile(id, version, 'adopt')}>Reconcile as delivered</button><button onClick={() => reconcile(id, version, 'no-effect')}>Reconcile as not delivered</button></p>}</article>;
  })}{hasMore && <button onClick={loadOlder} disabled={loadingOlder}>{loadingOlder ? 'Loading older runs…' : 'Load older runs'}</button>}</section>;
}
