/* The parser deliberately checks runtime delimiters after every token. */
/* eslint-disable @typescript-eslint/no-unnecessary-condition */
import { canonicalJson, ContractDescriptor, ContractEnvelope, ContractValidationError, digest, validateEnvelope } from './index.js';
const MAX_BYTES = 1_000_000;
function parseStrictJson(input: string): unknown {
  let offset = 0; const whitespace = /\s/u; const skip = (): void => { while (whitespace.test(input[offset] ?? '')) offset += 1; };
  const value = (): unknown => { skip(); const initial = input[offset]; if (initial === '{') return object(); if (initial === '[') return array(); if (initial === '"') return text(); const literal = /^(true|false|null)/u.exec(input.slice(offset)); if (literal) { const literalText = literal[1]; if (literalText === undefined) throw new ContractValidationError('INVALID_JSON', 'Malformed JSON.'); offset += literalText.length; return literalText === 'true' ? true : literalText === 'false' ? false : null; } const number = /^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/u.exec(input.slice(offset)); if (number) { offset += number[0].length; const parsed = Number(number[0]); if (!Number.isFinite(parsed)) throw new ContractValidationError('INVALID_JSON_NUMBER', 'Non-finite JSON number.'); return parsed; } throw new ContractValidationError('INVALID_JSON', 'Malformed JSON.'); };
  const text = (): string => { const start = offset; offset += 1; let escaped = false; while (offset < input.length) { const char = input[offset++] as string; if (!escaped && char === '"') return JSON.parse(input.slice(start, offset)) as string; if (!escaped && char < ' ') throw new ContractValidationError('INVALID_JSON', 'Malformed JSON string.'); escaped = !escaped && char === '\\'; if (char !== '\\') escaped = false; } throw new ContractValidationError('INVALID_JSON', 'Unterminated JSON string.'); };
  const object = (): Record<string, unknown> => { const result: Record<string, unknown> = {}; const seen = new Set<string>(); offset += 1; skip(); if (input[offset] === '}') { offset += 1; return result; } while (true) { skip(); if (input[offset] !== '"') throw new ContractValidationError('INVALID_JSON', 'Object key expected.'); const key = text(); if (seen.has(key)) throw new ContractValidationError('DUPLICATE_KEY', 'Duplicate JSON key.'); seen.add(key); skip(); if (input[offset++] !== ':') throw new ContractValidationError('INVALID_JSON', 'Colon expected.'); result[key] = value(); skip(); if (input[offset] === '}') { offset += 1; return result; } if (input[offset++] !== ',') throw new ContractValidationError('INVALID_JSON', 'Comma expected.'); } };
  const array = (): unknown[] => { const result: unknown[] = []; offset += 1; skip(); if (input[offset] === ']') { offset += 1; return result; } while (true) { result.push(value()); skip(); if (input[offset] === ']') { offset += 1; return result; } if (input[offset++] !== ',') throw new ContractValidationError('INVALID_JSON', 'Comma expected.'); } };
  const result = value(); skip(); if (offset !== input.length) throw new ContractValidationError('INVALID_JSON', 'Unexpected JSON content.'); return result;
}
export function decodeContract(descriptor: ContractDescriptor, input: string | Uint8Array, expectedTenantId?: string): ContractEnvelope { const bytes = typeof input === 'string' ? new TextEncoder().encode(input) : input; if (bytes.byteLength > MAX_BYTES) throw new ContractValidationError('PAYLOAD_TOO_LARGE', 'Contract payload is too large.'); let parsed: unknown; try { parsed = parseStrictJson(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); } catch (error) { if (error instanceof ContractValidationError) throw error; throw new ContractValidationError('INVALID_JSON', 'Malformed UTF-8 JSON.'); } const envelope = validateEnvelope(descriptor, parsed); if (expectedTenantId !== undefined && envelope.tenantId !== expectedTenantId) throw new ContractValidationError('TENANT_MISMATCH', 'Tenant scope does not match the route.'); return envelope; }
export async function encodeContract(descriptor: ContractDescriptor, envelope: ContractEnvelope, allowedPayloadKeys?: readonly string[]): Promise<{ bytes: Uint8Array; digest: string }> { const safe = allowedPayloadKeys === undefined ? envelope : { ...envelope, payload: Object.fromEntries(allowedPayloadKeys.filter((key) => key in envelope.payload).map((key) => [key, envelope.payload[key]])) }; validateEnvelope(descriptor, safe); const bytes = new TextEncoder().encode(canonicalJson(safe)); return { bytes, digest: await digest(safe) }; }
export async function transformContract(source: ContractDescriptor, target: ContractDescriptor, input: unknown, transform: (envelope: ContractEnvelope) => ContractEnvelope): Promise<{ envelope: ContractEnvelope; provenance: { sourceVersion: string; targetVersion: string; transformDigest: string } }> { if (source.classification !== target.classification) throw new ContractValidationError('UNSAFE_TRANSFORM', 'A transform cannot change classification.'); const sourceEnvelope = validateEnvelope(source, input); const transformed = validateEnvelope(target, transform(sourceEnvelope)); return { envelope: transformed, provenance: { sourceVersion: source.version, targetVersion: target.version, transformDigest: await digest(canonicalJson(transform.toString())) } }; }
