export const EVENTS = {
  'api.request.failed': ['tenant_id', 'route', 'method', 'status', 'code', 'category', 'correlation_id'],
  'auth.denied': ['route', 'reason'],
  'command.executed': ['tenant_id', 'owner', 'name', 'outcome', 'actor_user_id', 'object_id'],
  'run.started': ['tenant_id', 'run_id', 'definition_id', 'trigger', 'owner_id'],
  'run.finished': ['tenant_id', 'run_id', 'definition_id', 'status', 'reason', 'duration_s', 'tokens', 'cost'],
  'node.failed': ['tenant_id', 'run_id', 'node_id', 'node_kind', 'code'],
  'approval.requested': ['tenant_id', 'run_id', 'node_id', 'kind', 'capability', 'expires_at'],
  'approval.decided': ['tenant_id', 'run_id', 'decision', 'actor_user_id', 'wait_s'],
  'approval.expired': ['tenant_id', 'run_id', 'node_id'],
  'model.call': ['tenant_id', 'run_id', 'node_id', 'provider', 'model', 'attempt', 'outcome', 'tokens', 'cost', 'duration_s'],
  'mcp.call': ['tenant_id', 'run_id', 'node_id', 'capability', 'route', 'outcome', 'duration_s', 'effect_id'],
  'circuit.transition': ['tenant_id', 'kind', 'state'],
  'webhook.delivery': ['tenant_id', 'definition_id', 'outcome'],
  'connector.request': ['tenant_id', 'installation_id', 'operation', 'outcome'],
  'memory.retrieval': ['tenant_id', 'run_id', 'node_id', 'status', 'item_count'],
  'group.changed': ['group_id', 'action', 'actor_user_id', 'subject_id'],
  'assistant.asked': ['group_id', 'billing_tenant_id', 'provider', 'model', 'tokens', 'cost', 'outcome'],
} as const;
